[build]
  command = "npm ci && npm run build"
  publish = "_site"

[functions]
  directory = "netlify/functions"

[build.environment]
  NPM_FLAGS = "--include=dev"
  NODE_VERSION = "20"

[[redirects]]
  from = "https://notes.jchackett.me/notes/*"
  to = "/404"
  status = 404
  force = true

[[redirects]]
  from = "https://notes.jchackett.me/*"
  to = "/notes/:splat"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/:path/index.html"
  to = "/:path/"
  status = 301