[build]
  command = "npm ci && npm run build"
  publish = "_site"

[functions]
  directory = "netlify/functions"

[build.environment]
  NPM_FLAGS = "--include=dev"
  NODE_VERSION = "20"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/:path/index.html"
  to = "/:path/"
  status = 301